/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-22-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@IsTest
public with sharing class testafimigue2 {
    @IsTest
    static void test(){
        
        Test.startTest();
        tesafimigue2 obj = new tesafimigue2();
        Test.stopTest();
        
    }
}