# Workflow pr-on-qa f
name: Validate PR
on:
    pull_request:
      types: [opened, synchronize]
      branches: [ QA ]
      paths:
        - 'force-app/**'
#
permissions:
  security-events: write
  actions: read
  contents: 'read'
  pull-requests: write

jobs:
    validate-pr-in-QA:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: 'Read PR Body'
              env:
                PR_BODY: ${{github.event.pull_request.body}}
                BRANCH_NAME: ${{ github.head_ref }}
                GH_TOKEN: ${{ github.token }} 
              run: |         
                  echo $PR_BODY > ./pr_body.txt
                  node ./parsePR.js              
                  TESTS=$(cat testsToRun.txt)       
                  echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
                          
            
    Create-PR-UAT:
        needs: validate-pr-in-QA
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - name: create pull request
              env:
                  BRANCH_NAME: ${{ github.head_ref }}
                  GH_TOKEN: ${{ github.token }}
              run: 
                 gh pr create -B UAT -H $BRANCH_NAME --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
                  

                        
