# Workflow pr-on-qa f
name: Validate PR
on:
    pull_request:
      types: [opened, synchronize]
      branches: [ QA ]
      paths:
        - 'force-app/**'
#
permissions:
  security-events: write
  actions: read
  contents: 'read'
  pull-requests: write

jobs:
    validate-pr-in-QA:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: 'Read PR Body'
              env:
                PR_BODY: ${{github.event.pull_request.body}}
                BRANCH_NAME: ${{ github.head_ref }} 
              run: |
                  mkdir testing
                  echo $BRANCH_NAME  > testing/pr_branch.txt
                  echo nombre=$(cat testing/pr_branch.txt)
                  echo "artifactPath=testing/pr_branch.txt" >> $GITHUB_ENV            
                  echo $PR_BODY > ./pr_body.txt
                  node ./parsePR.js              
                  TESTS=$(cat testsToRun.txt)       
                  echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
            - uses: actions/upload-artifact@v3
              with: 
                name: brnameafi
                path: ${{ env.artifactPath }}                 
            
    Create-PR-UAT:
        needs: validate-pr-in-QA
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: actions/download-artifact@v3
              with: 
                name: brnameafi
                path: ${{ env.artifactPath }} 
            - name: create pull request
              run: 
                 echo
                 gh pr create -B UAT -H ${{ env.nombre }} --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
              env:
                  GH_TOKEN: ${{ github.token }}
                  

                        
